version: '2'
services: 
  fms2: 
    container_name: fms2
    ports:
    - 0:8080
    env_file: 
    - ./docker.env
    image: imageName
    restart: always
    volumes:
    - /tmp/logs:/tmp/logs
    logging:
      options:
        max-size: 10m
        max-file: '10'
networks:
  default:
    external:
      name: sfdockerelkmaster_elk
